---
config:
  theme: forest
---
sequenceDiagram
    participant user
    participant browser
    participant server

    user->>browser: user create a new note

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server-->>browser: HTML document
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: the css file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: the JavaScript file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: [{content: "note content", date: "2025-02-22T16:07:28.906Z"}]
    deactivate server

    browser->>user: the brower displays the note in the page
